#!/bin/sh -e
. ../common.sh

if [ -s $gwiptbl ] || [ "$(cat /tmp/boot_runs_$interface)" -ge 5 ]; then
	if test_connectivity internet; then
		logger -t fsm "Interface $interface: Node is online"
		echo queen
	elif cloud_is_online; then
		logger -t fsm "Interface $interface: Cloud is online"
		echo drone
	else
		logger -t fsm "Interface $interface: Cloud is offline"
		echo robinson
	fi
else
	boot_runs="$(cat /tmp/boot_runs_$interface)"
	boot_runs_new=`expr $boot_runs + 1`
	echo $boot_runs_new > /tmp/boot_runs_$interface
	logger -t fsm "Interface $interface: Waiting for network data"
	echo boot
fi
