#!/bin/sh -e
. ../common.sh
#Check if our current Oct3 is valid
CurrentOct3=$(current_oct3)
[ -n "$CurrentOct3" ]

# if our GW IP has been taken we must no use it again
if ! we_own_our_ip; then
	logger -t fsm "Interface $interface: We dont own our IP! Changing ..."
    if ! cloud_is_online; then
	echo robinson
    else
	echo drone
    fi
    exit
fi

if test_connectivity internet; then
	logger -t fsm "Interface $interface: Node is online"
    echo queen
    exit
fi

if [ "$SO" == "ghost" ]; then
    GhostTime=$(($(date +%s) - $(cat /tmp/ghost_since_$interface)))
else
    GhostTime=0
fi
if ! cloud_is_online; then
	logger -t fsm "Interface $interface: Cloud is offline"
    echo robinson
elif [ $GhostTime -ge $DHCPLeaseTime ]; then
	logger -t fsm "Interface $interface: Cloud is online"
    echo drone
else
	logger -t fsm "Interface $interface: Cloud is online"
    echo ghost
fi
